name: 'Snorkell DocGen Client'
description: 'Use this GitHub Action to create documentation PR of your recent main branch merge.'
author: 'snorkell.ai'

inputs:
  client_id:
    description: 'Client ID for Snorkell'
    required: true
  api_key:
    description: 'API Key for Snorkell'
    required: true
  branch_name:
    description: 'Base Branch for the PR'
    required: true
  style_guide:
    description: "Style guide for the documentation"
    required: false
outputs: {}

runs:
  using: 'composite'

  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Download Script and Install Dependencies
      run: |
        curl -o run_doc_gen.py https://raw.githubusercontent.com/SingularityX-ai/snorkell-documentation-client/v1.0.0/src/index.py
        pip install requests requests asyncio
      shell: bash

    - name: Prepare Commit Message
      id: prep
      shell: bash
      run: |
        ESCAPED_COMMIT_MSG=$(printf '%s\n' "${{ github.event.head_commit.message }}" | jq -R -s -c .)
        echo "::set-output name=escaped_commit_msg::$ESCAPED_COMMIT_MSG"

    - name: Run Script
      shell: bash
      env:
        SNORKELL_CLIENT_ID: ${{ inputs.client_id }}
        SNORKELL_API_KEY: ${{ inputs.api_key }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        BRANCH_NAME: ${{ inputs.branch_name }}
        GITHUB_SHA: ${{ github.sha }}
        COMMIT_MSG: ${{ steps.prep.outputs.escaped_commit_msg }}
        STYLE_GUIDE: ${{ inputs.style_guide }}

      run: |
        python -u run_doc_gen.py
         
branding:
  icon: 'upload-cloud'
  color: 'blue'
